name: pulsar-io-big-query unit tests

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: s4u/maven-settings-action@v2.6.0
      with:
        servers: '[{"id": "ossrh", "username": "${{ secrets.SONATYPE_USERNAME }}",
          "password": "${{ secrets.SONATYPE_PASSWORD }}"}]'
    - name: Login to cloudsmith
      run: docker login -u="${{ secrets.CLOUDSMITH_USERNAME }}" -p="${{ secrets.CLOUDSMITH_API_KEY
        }}" docker.cloudsmith.io
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: License check
      run: mvn license:check

    - name: Build with Maven skipTests
      run: mvn clean install -DskipTests

    - name: Style check
      run: mvn checkstyle:check

    - name: Spotbugs check
      run: mvn spotbugs:check

    - name: Run unit test
      run: mvn test -Dtest="*Test"  -DfailIfNoTests=false
